# Generated by Django 5.2.4 on 2025-07-31 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='marks',
            new_name='mark',
        ),
    ]
